# -*- coding: utf-8 -*-
"""sakthisasi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PZN1RFg0NsyQwgzllZwODfRsysNnD0eb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/train.csv')

df.info()

df2 = df.drop(['Unnamed: 17', 'Unnamed: 18'], axis =1)

df2.info()

df2.describe()

df2.fillna(0)

df2.info()

df2 = df2.fillna(0)

df2.info()

df2['Trend_day_count']= df2['Trend_day_count'].astype(float)

df2['dislike']= pd.to_numeric(df2['dislike'], errors = 'coerce')
df2['comment_count']= pd.to_numeric(df2['comment_count'], errors = 'coerce')
df2['Trend_tag_count']= pd.to_numeric(df2['Trend_tag_count'], errors = 'coerce')
df2['Tag_count']= pd.to_numeric(df2['Tag_count'], errors = 'coerce')
df2['category_id']= pd.to_numeric(df2['category_id'], errors = 'coerce')
df2['likes']= pd.to_numeric(df2['likes'], errors = 'coerce')

df2 = df2.fillna(0)

df2.info()

df2['like dislike disabled']= df2['like dislike disabled'].astype(bool)
df2['comment_disabled']= df2['comment_disabled'].astype(bool)
df2['tag appered in title']= df2['tag appered in title'].astype(bool)

df2.fillna(0)

df2.info()

sns.boxplot(df2['subscriber'])

sns.distplot(df2['dislike'])

sns.boxplot(df2['likes'])

sns.catplot(x="Trend_tag_count",y="Tag_count",data=df2,kind="bar",height=4)

sns.barplot(x= df2['Video_id'].head(), y= df2['Trend_day_count'].head())
sns.lineplot(x= df2['Video_id'].head(), y= df2['Trend_day_count'].head())

sns.countplot(x ='like dislike disabled', data=df2)

sns.countplot(x ='comment_disabled', data=df2)

sns.countplot(x ='tag appered in title', data=df2)

sns.violinplot(df2.Trend_day_count,df2.Trend_tag_count)

sns.regplot(x = df2.Trend_day_count, y = df2.Trend_tag_count)

sns.heatmap(data = df2.corr(), annot = True, linewidth=0.5,cmap = 'Blues', cbar = True,vmin=-1, vmax=1)